# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_box.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 500)
        Form.setStyleSheet("background-color: white;\n"
"")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(120, 120, 191, 16))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(57, 24, 71);\n"
"font: 63 8pt \"Montserrat SemiBold\";\n"
"")
        self.label.setObjectName("label")
        self.pw_f = QtWidgets.QLineEdit(Form)
        self.pw_f.setGeometry(QtCore.QRect(120, 230, 250, 31))
        self.pw_f.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-color: grey;\n"
"border-width: 1px;\n"
"border-radius: 5px;")
        self.pw_f.setText("")
        self.pw_f.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pw_f.setObjectName("pw_f")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(120, 210, 191, 16))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        font.setKerning(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(57, 24, 71);\n"
"font: 63 8pt \"Montserrat SemiBold\";\n"
"")
        self.label_3.setObjectName("label_3")
        self.login_u = QtWidgets.QLabel(Form)
        self.login_u.setGeometry(QtCore.QRect(120, 90, 50, 2))
        self.login_u.setStyleSheet("background-color: rgb(57, 24, 71);")
        self.login_u.setText("")
        self.login_u.setObjectName("login_u")
        self.login_b = QtWidgets.QPushButton(Form)
        self.login_b.setGeometry(QtCore.QRect(120, 300, 251, 41))
        self.login_b.setStyleSheet("background-color: rgb(180, 145, 76);\n"
"font: 12pt \"Montserrat SemiBold\";\n"
"color: white;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 5px;")
        self.login_b.setObjectName("login_b")
        self.new_acc_u = QtWidgets.QLabel(Form)
        self.new_acc_u.setGeometry(QtCore.QRect(248, 90, 100, 1))
        self.new_acc_u.setStyleSheet("background-color: rgb(57, 24, 71);")
        self.new_acc_u.setText("")
        self.new_acc_u.setObjectName("new_acc_u")
        self.un_f = QtWidgets.QLineEdit(Form)
        self.un_f.setGeometry(QtCore.QRect(120, 140, 250, 31))
        self.un_f.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font-color: black;\n"
"border-style: outset;\n"
"border-color: grey;\n"
"border-width: 1px;\n"
"border-radius: 5px;")
        self.un_f.setObjectName("un_f")
        self.na_b = QtWidgets.QPushButton(Form)
        self.na_b.setGeometry(QtCore.QRect(240, 60, 120, 25))
        self.na_b.setStyleSheet("background-color: white;\n"
"font: 8pt \"Montserrat\";\n"
"color: rgb(57, 24, 71);\n"
"border-style: outset;")
        self.na_b.setObjectName("na_b")
        self.login_b_2 = QtWidgets.QPushButton(Form)
        self.login_b_2.setGeometry(QtCore.QRect(120, 60, 50, 25))
        font = QtGui.QFont()
        font.setFamily("Montserrat Semibold")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.login_b_2.setFont(font)
        self.login_b_2.setStyleSheet("background-color: white;\n"
"font: 8pt \"Montserrat Semibold\";\n"
"color: rgb(57, 24, 71);\n"
"border-style: outset;")
        self.login_b_2.setObjectName("login_b_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Login to Algonquin University"))
        self.label.setText(_translate("Form", "USERNAME"))
        self.label_3.setText(_translate("Form", "PASSWORD"))
        self.login_b.setText(_translate("Form", "LOGIN"))
        self.na_b.setText(_translate("Form", "NEW ACCOUNT"))
        self.login_b_2.setText(_translate("Form", "LOGIN"))
